name: edit_builder
description: Simple package to help on creation of edit pages.
version: 0.0.1
homepage: https://github.com/jesusrp98/flutter_packages/

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
