name: edit_builder
description: Simple package to help on creation of edit pages.
version: 0.1.0
homepage: https://github.com/jesusrp98/flutter_packages/

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ">= 6.0.0 <7.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
